### ISSUE TITLE
Suggestion: Create a "colorized" Adapta theme for arcolinux

### ISSUE THREAD

**Issue by spsf64** [arcolinux/arcolinux_repo#1]
Like you did with "arcolinux-arc-themes"
I like adapta theme (the -eta variant) because it is more compact than arc theme.
https://github.com/adapta-project/adapta-gtk-theme
Thanks for this great project!

**Comment by spsf64** [comment]
I found this project
https://github.com/fold0/adapta-gtk-theme-colorpack
However it does not change color in XFCE top bar...
Maybe you find a way to create a new pack

**Comment by arcolinuxz** [comment]
written in my to do if and when
