### ISSUE TITLE
FastFetch Breaks pacman

### ISSUE THREAD

**Issue by Burnsedia** [arcolinux/arcolinux_repo#3]
I installed fastfetch and for some reason I can nolonger update my system. I can even remove fastfetch.

**Comment by arcolinuxz** [comment]
i suppose you figured it out already

**Comment by Burnsedia** [comment]
I just had to reinstall the OS, every package PGP key was corrupted

**Comment by arcolinuxz** [comment]
you will figure out what you did wrong
