### ISSUE TITLE
bug : `alt + tab` is not working   

### ISSUE THREAD

**Issue by Tuhinm2002** [arcolinux/arcolinux_repo#4]
The `alt+tab` key combination is not working for switching windows in xfce4 edition of the linux. This started to occur after I upgraded to the version 24.10

**Comment by DeltaCopy** [comment]
@Tuhinm2002 this is not the right repository to raise this issue.
xfce4 is a package which comes from Archlinux.

If you have a specific issue with Arco then please raise this either on the forums or discord/telegram.

**Comment by arcolinuxz** [comment]
it is actually working on my newly installed arconet xfce offline

ALT + TAB is giving a nice image of every open window and I can change
between them
